server:
  port: 8888


#应用名称
spring:
  application:
    name: dcloud-gateway

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.150.146:8848
        username: nacos
        password: nacos


