server:
  port: 8001


#应用名称
spring:
  application:
    name: dcloud-account

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.228.46:8848
        username: nacos
        password: nacos

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.198.228.46:13306/dcloud_account-plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://localhost:3306/dcloud_account-plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xdclass.net168



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

